/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import {MathUtils} from 'three'
import React, {useRef} from 'react'
import {useGLTF} from '@react-three/drei'
import {GLTF} from 'three-stdlib'
import {useFrame} from "@react-three/fiber";
import {HasPhase, RADIUS} from "../LogoOrbit";

type GLTFResult = GLTF & {
    nodes: {
        Curve: THREE.Mesh
        Curve002: THREE.Mesh
    }
    materials: {
        ['SVGMat.001']: THREE.MeshStandardMaterial
        ['SVGMat.003']: THREE.MeshStandardMaterial
    }
}

export default function Model({...props}: JSX.IntrinsicElements['group'] & HasPhase) {
    const group = useRef<THREE.Group>()
    const {nodes, materials} = useGLTF('/java.gltf') as GLTFResult


    useFrame(({clock}) => {
        if (!group?.current) return

        const time = clock.getElapsedTime() / 4
        const {phase} = props
        const x = RADIUS * Math.sin(time + phase)
        const y = RADIUS * Math.cos(time + phase)
        const z = RADIUS * Math.sin(time + phase) / 4

        group.current.position.set(x, z, y)
    })

    return (
        <group ref={group} {...props} dispose={null}>
            <mesh geometry={nodes.Curve.geometry} material={materials['SVGMat.001']} position={[-0.01, 0, 0.4]}/>
            <mesh geometry={nodes.Curve002.geometry} material={materials['SVGMat.003']} position={[0.01, 0, -0.4]}/>
        </group>
    )
}

useGLTF.preload('/java.gltf')
