/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import {MathUtils} from 'three'
import React, {useRef} from 'react'
import {useGLTF} from '@react-three/drei'
import {GLTF} from 'three-stdlib'
import {useFrame} from "@react-three/fiber";

type GLTFResult = GLTF & {
    nodes: {
        Curve: THREE.Mesh
        Curve002: THREE.Mesh
    }
    materials: {
        ['SVGMat.001']: THREE.MeshStandardMaterial
        ['SVGMat.003']: THREE.MeshStandardMaterial
    }
}

const Radius = 3

const rad90deg = MathUtils.degToRad(90)

export default function Model({...props}: JSX.IntrinsicElements['group']) {
    const group = useRef<THREE.Group>()
    const {nodes, materials} = useGLTF('/java.gltf') as GLTFResult

    useFrame(({clock}) => {
        if (!group.current) return;

        const time = clock.getElapsedTime() / 2
        group.current.position.x = Radius * Math.sin(time)
        group.current.position.z = Radius * Math.cos(time)
        group.current.position.y = Radius * Math.sin(time) / 4
        group.current.rotation.z = time * 2
    })

    return (
        <group ref={group} scale={[0.2, 0.2, 0.2]} rotation={[rad90deg, 0, 0]} {...props} dispose={null}>
            <mesh geometry={nodes.Curve.geometry} material={materials['SVGMat.001']} position={[-0.01, 0, 0.4]}/>
            <mesh geometry={nodes.Curve002.geometry} material={materials['SVGMat.003']} position={[0.01, 0, -0.4]}/>
        </group>
    )
}

useGLTF.preload('/java.gltf')
