/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, {useRef} from 'react'
import {useGLTF} from '@react-three/drei'
import {GLTF} from 'three-stdlib'
import {HasPhase, RADIUS} from "../LogoOrbit";
import {useFrame} from "@react-three/fiber";

type GLTFResult = GLTF & {
    nodes: {
        Curve: THREE.Mesh
    }
    materials: {
        ['SVGMat.001']: THREE.MeshStandardMaterial
    }
}

export default function Model({...props}: JSX.IntrinsicElements['group'] & HasPhase) {
    const group = useRef<THREE.Group>()
    const {nodes, materials} = useGLTF('/models/logos/git.gltf') as GLTFResult

    useFrame(({clock}) => {
        if (!group?.current) return

        const time = clock.getElapsedTime() / 4
        const {phase} = props
        const x = RADIUS * Math.sin(time + phase)
        const y = RADIUS * Math.cos(time + phase)
        const z = RADIUS * Math.sin(time + phase) / 4

        group.current.position.set(x, z, y)
    })

    return (
        <group ref={group} {...props} dispose={null}>
            <mesh geometry={nodes.Curve.geometry} material={materials['SVGMat.001']}/>
        </group>
    )
}

useGLTF.preload('/models/logos/git.gltf')
