/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, {useRef} from 'react'
import {useGLTF} from '@react-three/drei'
import {GLTF} from 'three-stdlib'
import {HasPhase, RADIUS} from "../LogoOrbit";
import {useFrame} from "@react-three/fiber";

type GLTFResult = GLTF & {
    nodes: {
        Curve: THREE.Mesh
        Curve001: THREE.Mesh
        Curve002: THREE.Mesh
        Curve003: THREE.Mesh
    }
    materials: {
        ['SVGMat.001']: THREE.MeshStandardMaterial
        ['SVGMat.002']: THREE.MeshStandardMaterial
        ['SVGMat.003']: THREE.MeshStandardMaterial
        ['SVGMat.004']: THREE.MeshStandardMaterial
    }
}

export default function Model({...props}: JSX.IntrinsicElements['group'] & HasPhase) {
    const group = useRef<THREE.Group>()
    const {nodes, materials} = useGLTF('/models/logos/html.gltf') as GLTFResult

    useFrame(({clock}) => {
        if (!group?.current) return

        const time = clock.getElapsedTime() / 4
        const {phase} = props
        const x = RADIUS * Math.sin(time + phase)
        const y = RADIUS * Math.cos(time + phase)
        const z = RADIUS * Math.sin(time + phase) / 4

        group.current.position.set(x, z, y)
    })

    return (
        <group ref={group} {...props} dispose={null}>
            <mesh geometry={nodes.Curve.geometry} material={materials['SVGMat.001']} position={[0, 0, -0.01]}/>
            <mesh geometry={nodes.Curve001.geometry} material={materials['SVGMat.002']} position={[0.32, 0, 0.01]}/>
            <mesh geometry={nodes.Curve002.geometry} material={materials['SVGMat.003']} position={[-0.27, 0, 0.02]}
                  scale={[1, 0.71, 1]}/>
            <mesh geometry={nodes.Curve003.geometry} material={materials['SVGMat.004']} position={[0.25, 0, 0.03]}
                  scale={[1, 0.86, 1]}/>
        </group>
    )
}

useGLTF.preload('/models/logos/html.gltf')
